apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-fjgiydhk
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: tssc-quay-quay-tssc-quay.apps.cluster-fhj8w.fhj8w.sandbox2412.opentlc.com/tssc/go-fjgiydhk:fd9b9da2f2e9b8fbb50029a16d1028e987155ef3@sha256:ca4bc54832fd6376e5d2098fcfcf856e8aa43db8a8a6df923f3fce8362fe27ba
          name: container-image
